import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionWrapper } from "./providers/provider-session";
import { ReactNode, Suspense } from "react";
import { withAuth } from "next-auth/middleware";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper session={session}>
          <Suspense>{children}</Suspense>
        </SessionWrapper>
      </body>
    </html>
  );
}
